name: _buildx
on:
  workflow_call:
    inputs:
      pkg_type:
        default: static
        required: false
        type: string

env:
  _REPO_THIS: "_repo_this"
  _REPO_PKGS: "_repo_pkgs"
  _PUSH: false

jobs:
  _buildx:
    strategy:
      matrix:
        include:
          - platform: 'iphoneos'
            arch: 'arm64'
          - platform: 'iphonesimulator'
            arch: 'arm64'
          - platform: 'iphonesimulator'
            arch: 'x86_64'
          - platform: 'macosx'
            arch: 'arm64'
          - platform: 'macosx'
            arch: 'x86_64'
    runs-on: macos-14
    steps:
      - name: set env `_PUSH=true`
        if: ${{ github.event_name == 'push' }}
        run: echo "_PUSH=true" >> "$GITHUB_ENV"
      - name: checkout this repo
        uses: actions/checkout@v4
        with:
          path: ${{ env._REPO_THIS }}
      - name: checkout pre-compiled packages repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/packages
          path: ${{ env._REPO_PKGS }}
      - name: show debug info
        run: |
          env
          echo -e "\n"
          echo -e "${PWD}"
          echo -e "\n"
          ls -Alh -- ${_REPO_THIS}
          echo -e "\n"
          ls -Alh -- ${_REPO_PKGS}
      - name: buildx library - ${{ github.workflow }}
        run: |
          source ${{ env._REPO_THIS }}/build-${{ matrix.platform }}-${{ matrix.arch }}.sh
          compile ${{ github.workflow }} ${{ inputs.pkg_type }} ${{ matrix.platform }} ${{ matrix.arch }}
      - name: upload library - ${{ github.workflow }}
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ${{ env._REPO_THIS }}/out/${{ github.workflow }}/${{ matrix.platform }}/${{ matrix.arch }}
