name: _buildx
on:
  workflow_call:
    inputs:
      pkg_type:
        default: static
        required: false
        type: string

jobs:
  _buildx:
    strategy:
      matrix:
        include:
          # - platform: 'iphoneos'
          #   arch: 'arm64'
          # - platform: 'iphonesimulator'
          #   arch: 'arm64'
          # - platform: 'iphonesimulator'
          #   arch: 'x86_64'
          # - platform: 'macosx'
          #   arch: 'arm64'
          - platform: 'macosx'
            arch: 'x86_64'
    runs-on: macos-14
    outputs:
      version: ${{ steps.version.outputs._PKG_VERSION }}
    env:
      _REPO_THIS: "_repo_this"
      INST_DIR: "${{ github.workspace }}/${{ github.workflow }}"
    steps:
      - name: checkout this repo
        uses: actions/checkout@v4
        with:
          path: ${{ env._REPO_THIS }}
      - name: buildx library - ${{ github.workflow }}
        run: |
          source ${{ env._REPO_THIS }}/build-${{ matrix.platform }}-${{ matrix.arch }}.sh
          compile ${{ github.workflow }} ${{ inputs.pkg_type }} ${{ matrix.platform }} ${{ matrix.arch }}
      - name: set required env `_PKG_VERSION`
        id: version
        run: |
          pushd -- "${{ env._REPO_THIS }}/deps/${{ github.workflow }}"
          _PKG_VERSION=$(git describe --tags --always --abbrev=7)
          popd

          echo "_PKG_VERSION=${_PKG_VERSION}" >> "$GITHUB_ENV"
          echo "_PKG_VERSION=${_PKG_VERSION}" >> "$GITHUB_OUTPUT"
      - name: set required env `_PKG_ZIP_NAME`
        run: |
          echo "_PKG_ZIP_NAME=${{ github.workflow }}_${{ matrix.platform }}_${{ matrix.arch }}_${{ env._PKG_VERSION }}_${{ inputs.pkg_type }}.zip" >> "$GITHUB_ENV"
      - name: compress library - ${{ github.workflow }}
        run: |
          zip -q -ry "${{ env._PKG_ZIP_NAME }}" ${{ github.workflow }}
      - name: show debug info
        run: |
          env
          echo -e "\n"
          echo -e "${PWD}"
          echo -e "\n"
          ls -Alh -- .
          echo -e "\n"
          ls -Alh -- ${_REPO_THIS}
      - name: upload library - ${{ github.workflow }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env._PKG_ZIP_NAME }}
          path: ${{ env._PKG_ZIP_NAME }}
  _upload:
    needs: _buildx
    runs-on: ubuntu-latest
    env:
      _PUSH: false
    steps:
      - name: set env `_PUSH=true`
        if: ${{ github.event_name == 'push' }}
        run: echo "_PUSH=true" >> "$GITHUB_ENV"
      - name: download ${{ inputs.pkg_type }} libraries
        uses: actions/download-artifact@v4
        with:
          path: ${{ github.workflow }}
          pattern: ${{ github.workflow }}_*_${{ inputs.pkg_type }}*.zip
      - name: set required env `_PKG_BRANCH`
        run: |
          echo "_PKG_BRANCH=${{ github.workflow }}/${{ needs._buildx.outputs.version }}/${{ github.run_id }}/${{ inputs.pkg_type }}" >> "$GITHUB_ENV"
      - name: upload to pre-compiled packages
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: git@github.com:${{ github.repository_owner }}/packages.git
          BRANCH: ${{ env._PKG_BRANCH }}
          FOLDER: ${{ github.workflow }}
          TARGET_DIR: ${{ github.workflow }}/${{ needs._buildx.outputs.version }}
          COMMIT_NAME: ${{ github.repository_owner }}
          COMMIT_EMAIL: ${{ github.run_id }}@gh-action.com
          MESSAGE: "gh action: ${{ env._PKG_BRANCH }}"
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY_REPO_PACKAGES }}
      - name: create pre-compiled packages pr
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create -B "${{ env._PKG_BRANCH }}" -H 'main' \
            -R '${{ github.repository_owner }}/packages' \
            -t "update library - ${{ github.workflow }}@${{ needs._buildx.outputs.version }} ${{ inputs.pkg_type }}" \
            -b "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
