name: mbedtls
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/mbedtls.yml'
      - 'deps/mbedtls'
      - 'patchs/mbedtls/**'
      - 'scripts/mbedtls.sh'
      - 'build.sh'
      - 'env-apple.sh'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/mbedtls.yml'
      - 'deps/mbedtls'
      - 'patchs/mbedtls/**'
      - 'scripts/mbedtls.sh'
      - 'build.sh'
      - 'env-apple.sh'

jobs:
  build:
    strategy:
      matrix:
        type: ['static', 'shared']
    secrets: inherit
    uses: ./.github/workflows/_buildx.yml
    with:
      pkg_type: ${{ matrix.type }}
